language: android
dist: trusty
sudo: false
notifications:
  email: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"

jobs:
  include:
    - stage: build
      name: build
      script: ./gradlew build
