language: android

notifications:
  email: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "build-tools;29.0.3"

jobs:
  include:
    - stage: build
      name: build
      script: ./gradlew build
    - stage: detekt & lint
      name: detekt & lint
      script: ./gradlew detekt lint

