language: android
dist: trusty
sudo: false
notifications:
  email: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

jobs:
  include:
    - stage: build
      name: build
      script: ./gradlew build
